- name: Create ~/code directory
  file:
    path: "{{ dotfiles_user_home }}/code"
    state: directory
    mode: '0755'

- name: Create .env template with API key stubs
  template:
    src: .env.template
    dest: "{{ dotfiles_user_home }}/code/.env"
    mode: '0600'
    force: no  # Don't overwrite existing file

- name: Create .gitignore for ~/code
  copy:
    content: |
      # Environment files
      .env
      .env.local
      .env.*.local
      
      # Secrets
      *.key
      *.pem
      credentials.json
      
      # IDE
      .vscode/settings.json
      .idea/
    dest: "{{ dotfiles_user_home }}/code/.gitignore"
    mode: '0644'

- name: Ensure Node.js is available via mise
  command: mise install node
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  failed_when: false

- name: Install Mac-CLI via npm
  npm:
    name: mac-cli
    global: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin"
  failed_when: false
  retries: 2
  delay: 5