
{
  homebrew = {
    enable = true;

    brews = [
      "ag", # Code-search similar to ack,
      "airshare", # Cross-platform content sharing in a local network,
      "amass", # In-depth Attack Surface Mapping and Asset Discovery,
      # "apparency", # Error: No available formula with the name "apparency". Did you mean apparix?,
      "atuin", # Improved shell history for zsh and bash
      "awk", # Text processing scripting language,
      "awscli", # Official Amazon AWS command-line interface,
      "bandwhich", # Terminal bandwidth utilization tool,
      "bash-completion@2", # Programmable completion for Bash 4.2+,
      "bash-git-prompt", # Informative, fancy bash prompt for Git users,
      "bat", # Clone of cat(1) with syntax highlighting and Git integration,
      "blueutil", # Get/set bluetooth power and discoverable state,
      "bottom", # Yet another cross-platform graphical process/system monitor,
      "broot", # New way to see and navigate directory trees,
      "brotli", # Generic-purpose lossless compression algorithm by Google,
      "carthage", # Decentralized dependency manager for Cocoa,
      "ca-certificates", # Mozilla CA certificate store,
      "cairo", # Vector graphics library with cross-device output support,
      "cgit", # Hyperfast web frontend for Git repositories written in C,
      "choose", # Make choices on the command-line,
      "click", # Command-line interactive controller for Kubernetes,
      "coreutils", # GNU File, Shell, and Text utilities,
      "create-dmg", # Shell script to build fancy DMGs,
      "ctags", # Reimplementation of ctags(1),
      "dex2jar", # Tools to work with Android .dex and Java .class files,
      "d2", # Modern diagram scripting language that turns text to diagrams,
      "direnv", # Load/unload environment variables based on $PWD,
      "docker", # Pack, ship and run any application as a lightweight container,
      "docker-compose", # Isolated development environments using Docker,
      "docutils", # Text processing system for reStructuredText,
      "dog", # Command-line DNS client,
      "dns2tcp", # TCP over DNS tunnel,
      # "dnslookup", # Error: No available formula with the name "dnslookup". Did you mean dnstop?,
      "dua-cli", # View disk space usage and delete unwanted data, fast,
      "duf", # Disk Usage/Free Utility - a better 'df' alternative,
      "dust", # More intuitive version of du in rust,
      "exa", # Modern replacement for 'ls',
      "faiss", # Efficient similarity search and clustering of dense vectors,
      "fbthrift", # Facebook's branch of Apache Thrift, including a new C++ server,
      "fd", # Simple, fast and user-friendly alternative to find,
      "ffmpeg", # Play, record, convert, and stream audio and video,
      "findutils", # Collection of GNU find, xargs, and locate,
      "flarectl", # CLI application for interacting with a Cloudflare account,
      "fff", # Simple file manager written in bash,
      "git", # Distributed revision control system,
      "git-delta", # Syntax-highlighting pager for git and diff output,
      "git-extras", # Small git utilities,
      "git-lfs", # Git extension for versioning large files,
      "git-tools", # Assorted git-related scripts and tools,
      "gh", # GitHub command-line tool,
      "glances", # Alternative to top/htop,
      "go", # Open source programming language to build simple/reliable/efficient software,
      "gnutls",
      "gping", # Ping, but with a graph,
      "grip", # GitHub Markdown previewer,
      "gum", # Tool for glamorous shell scripts,
      "gawk", # GNU awk utility,
      # "gnu", # Error: No available formula with the name "gnu". Did you mean gdu, gau or vnu?,
      "gnu-getopt", # Command-line option parsing utility,
      "gnu-indent", # C code prettifier,
      "gnu-sed", # GNU implementation of the famous stream editor,
      "gnu-tar", # GNU version of the tar archiving utility,
      "grep",
      "hashpump", # Tool to exploit hash length extension attack,
      "has", # Checks presence of various command-line tools and their versions on the path,
      "helm", # Kubernetes package manager,
      "heroku-node", # node.js dependency for heroku,
      "highlight", # Convert source code to formatted tex with syntax highlighting,
      "htmlq", # Uses CSS selectors to extract bits content from HTML files,
      "hopenpgp-tools", # Command-line tools for OpenPGP-related operations,
      "htop", # Improved top (interactive process viewer),
      "hydra", # Network logon cracker which supports many services,
      "hyperfine", # Command-line benchmarking tool,
      "iredis", # Terminal Client for Redis with AutoCompletion and Syntax Highlighting,
      "jc", # Serializes the output of command-line tools to structured JSON output,
      "jq", # Lightweight and flexible command-line JSON processor,
      "jsonlint", # JSON parser and validator with a CLI,
      "just", # Handy way to save and run project-specific commands,
      "keepassxc", # Cross-platform password manager,
      "mac"
      "keychain", # User-friendly front-end to ssh-agent(1),
      "knock", # Port-knock server,
      "lame", # High quality MPEG Audio Layer III (MP3) encoder,
      "lf", # Terminal file manager,
      "libassuan", # Assuan IPC Library,
      "libpq", # Postgres C API library,
      "llm", # Access large language models from the command-line,
      "localstack-cli",
      "locateme", # Find your location using Apple's geolocation services,
      "lsd", # Clone of ls with colorful output, file type icons, and more,
      "lua", # Powerful, lightweight programming language,
      "macvim", # GUI for vim, made for macOS,
      "mackup", # Keep your Mac's application settings in sync,
      "mas", # Mac App Store command-line interface,
      "m-cli", # Swiss Army Knife for macOS
      "mc", # Terminal-based visual file manager,
      "mcfly", # Fly through your shell history,
      "mc", # Terminal-based visual file manager,
      "mpg123", # MP3 player for Linux and UNIX,
      "ncrack", # Error: Cask 'ncrack' is unavailable: No Cask with this name exists.,
      "nmap", # Port scanning utility for large networks,
      "nnn", # Tiny, lightning fast, feature-packed file manager,
      "node", # Platform built on V8 to build network applications,
      "noti", # Trigger notifications when a process completes,
      # "npm yarn", # Error: No available formula with the name "npm yarn".,
      "onnxruntime", # Cross-platform, high performance scoring engine for ML models,
      "openjdk", # Development kit for the Java programming language,
      "openssl", # Cryptography and SSL/TLS Toolkit,
      "openssl-osx-ca", # https://github.com/raggi/openssl-osx-ca#readme,
      "pandoc", # Swiss-army knife of markup format conversion,
      # "pass", # open-source unix-based password utilitiy
      # "pass-otp", # Pass extension for managing one-time-password (OTP) tokens
      # "passpie",
      # "pc2", # Error: No available formula with the name "pc2". Did you mean pcb, pcp, pcl or pce?,
      "perl", # Highly capable, feature-rich programming language,
      "pgcli", # CLI for Postgres with auto-completion and syntax highlighting,
      "pinentry", # Passphrase entry dialog utilizing the Assuan protocol,
      "pipx", # Execute binaries from Python packages in isolated environments,
      "pcre2", # Perl compatible regular expressions library with a new API,
      "pre-commit",
      "procs", # Modern replacement for ps written by Rust,
      "postgresql@15", # Object-relational database system,
      "pulumi", # Cloud native development platform,
      "pyenv", # Python version management,
      "pyenv-virtualenv", # Pyenv plugin to manage virtualenv,
      "python@3.11", # Interpreted, interactive, object-oriented programming language,
      # "qlcolorcode", # Error: No available formula with the name "qlcolorcode". Did you mean color-code?,
      # "qlimagesize", # Error: No available formula with the name "qlimagesize".,
      # "qlmarkdown", # Error: No available formula with the name "qlmarkdown". Did you mean markdown?,
      # "quicklook-json", # Error: No available formula with the name "quicklook-json". Did you mean quick-lint-js?,
      # "quicklookase", # Error: No available formula with the name "quicklookase". Did you mean quictls?,
      # "qlstephen", # Error: No available formula with the name "qlstephen".,
      # "qlvideo", # Error: No available formula with the name "qlvideo".,
      "readline", # Library for command-line editing,
      "redis", # Persistent key-value database, with built-in net interface,
      "remake", # GNU Make with improved error handling, tracing, and a debugger,
      "rich-cli", # Command-line toolbox for fancy output in the terminal,
      "ripgrep", # Search tool like grep and The Silver Searcher,
      "rm-improved", # Command-line deletion tool focused on safety, ergonomics, and performance,
      "ruby", # Powerful, clean, object-oriented scripting language,
      "rust", # Safe, concurrent, practical language,
      "screenresolution", # Get, set, and list display resolution,
      "sd", # Intuitive find & replace CLI,
      "skhd", # Simple hotkey-daemon for macOS.,
      "sqlite", # Command-line interface for SQLite,
      "subversion", # Version control system designed to be a better CVS,
      # "suspicious-package", # Error: No available formula with the name "suspicious-package". Did you mean psc-package?,
      "task", # Feature-rich console based todo list manager,
      "tcptrace", # Analyze tcpdump output,
      "telnet", # User interface to the TELNET protocol,
      "terraform", # Tool to build, change, and version infrastructure,
      "testssl", # Tool which checks for the support of TLS/SSL ciphers and flaws,
      "tfvar", # Terraform's variable definitions template generator.,
      "thefuck", # Programmatically correct mistyped console commands,
      "tig", # Text interface for Git repositories,
      "tldr", # Simplified and community-driven man pages,
      "tidy-html5", # Granddaddy of HTML tools, with support for modern standards,
      "trailscraper", # Tool to get valuable information out of AWS CloudTrail,
      "terraform", # Error: No available formula with the name "terrafrom". Did you mean terraform?,
      "up", # Tool for writing command-line pipes with instant live preview,
      "unixodbc", # ODBC 3 connectivity for UNIX,
      "vale", # Syntax-aware linter for prose,
      "virtualenv", # Tool for creating isolated virtual python environments,
      # "vs-code", # Error: No available formula with the name "vs-code".,
      "w3m", # Pager/text based browser,
      "watch", # Executes a program periodically, showing output fullscreen,
      "watchman", # Watch files and take action when they change,
      "wget", # Internet file retriever,
      "whatmask", # Network settings helper,
      "whalebrew", # Homebrew, but with Docker images,
      "wifi-password", # Show the current WiFi network password,
      "wireshark", # Graphical network analyzer and capture tool,
      "xh", # Friendly and fast tool for sending HTTP requests,
      "xray", # Platform for building proxies to bypass network restrictions,
      "yank", # Copy terminal output to clipboard,
      "ykman", # Tool for managing your YubiKey configuration,
      "ykpers", # YubiKey personalization library and tool,
      "youtube-dl", # Download YouTube videos from the command-line,
      "yq", # Process YAML, JSON, XML, CSV and properties documents from the CLI,
      # "ytop", # Error: No available formula with the name "ytop". Did you mean mytop?,
      "zmap", # Network scanner for Internet-wide network studies,
      "zoxide", # Shell extension to navigate your filesystem faster,
      "zx", # Tool for writing better scripts
    ];

    casks = [
      "alfred4", # Application launcher and productivity software,
      "betterzip", # Utility to create and modify archives,
      "cakebrew", # GUI app for Homebrew,
      "devtoys", # Utilities designed to make common development tasks easier,
      "fiscript", # execute custom scripts on your files/folders from the context menu in Finder      "font-fira-code", # Free monospaced font with programming ligatures,
      "font-hack-nerd-font", # Developer targeted fonts with a high number of glyphs,
      "font-menlo-for-powerline", # None,
      "font-source-code-pro", # None,
      "google-chrome", # Web browser,
      "google-drive", # Client for the Google Drive storage service,
      "hammerspoon", # Desktop automation application,
      "handbrake", # Open-source video transcoder,
      "iina", # Free and open-source media player,
      "imageoptim", # Tool to optimize images to a smaller size,
      "insomnia", # HTTP and GraphQL Client,
      "key-codes", # Display key code, unicode value and modifier keys state for any key combination,
      "lark", # Project management software,
      "linkliar", # Link-Layer MAC spoofing GUI for macOS,
      "macvim", # Text editor,
      "menubarx", # Menu bar browser,
      "mullvadvpn", # VPN client,
      # "ncrack", # Error: Cask 'ncrack' is unavailable: No Cask with this name exists.,
      "noti", # Utility to show notifications from an Android device,
      "notion", # App to write, plan, collaborate, and get organized,
      "obsidian", # Knowledge base that works on top of a local folder of plain text Markdown files,
      # "pieces", # Error: Cask 'pieces' is unavailable: No Cask with this name exists.,
      "pieces-cli", # Command-line tool for Pieces.app,
      "qbittorrent", # Peer to peer Bitorrent client,
      "signal", # Instant messaging application focusing on security,
      "slack", # Team communication and collaboration software,
      "sloth", # Displays all open files and sockets in use by all running processes,
      "spotify", # Music streaming service,
      "stats", # System monitor for the menu bar,
      "suspicious-package", # Application for inspecting installer packages,
      "tailscale", # Mesh VPN based on Wireguard,
      "telegram", # Messaging app with a focus on speed and security,
      "textsniper", # Extract text from images and other digital documents in seconds,
      "todoist", # To-do list,
      "vlc", # Multimedia player,
      "vscodium", # Binary releases of VS Code without MS branding/telemetry/licensing,
      "wireshark", # Network protocol analyzer,
      "xbar", # View output from scripts in the menu bar,
      # "xray", # Error: Cask 'xray' is unavailable: No Cask with this name exists.,
      "zenmap", # Multi-platform graphical interface for official Nmap Security Scanner,
      "zoom", # Video communication and virtual meeting platform
    ];
  };

    taps = [
      "localstack/tap",
    ];
  };

    masApps = [
    ];
  };
}
