# TODO: fix: move backup tasks from Ansible to Invoke
- name: "Stop all containers"
  shell: "docker ps -q | xargs docker stop"
  # No containers might be running
  ignore_errors: true
  register: last_execution_docker
  when: "'docker_stop_containers' | run_only_after"

- name: "List all volumes related to a Docker Compose project"
  command: "docker volume ls --filter label=com.docker.compose.project -q"
  register: docker_compose_volumes
  when: last_execution_docker is not skipped

- name: "Create {{ backup_dir }}/docker_volumes/"
  file:
    state: directory
    path: "{{ backup_dir }}/docker_volumes/"

- name: "Backup each volume in {{ backup_dir }}/docker_volumes/"
  command: "docker-volume backup {{ backup_dir }}/docker_volumes/ {{ item }}"
  with_items: "{{ docker_compose_volumes.stdout_lines }}"
  when: last_execution_docker is not skipped

- name: "Copy Mackup default configuration from Ansible Mackup role to ~/.mackup.cfg"
  copy:
    src: "files/mackup.cfg"
    dest: "~/.mackup.cfg"
    force: true
  when: not (lookup('file', '~/.mackup.cfg') is defined)

- name: "Run Mackup in {{ backup_dir }} as root"
  command: "mackup backup -r --force --directory {{ backup_dir }}"
  become: true
  when: lookup('file', '~/.mackup.cfg') is defined