- name: "Install apt packages"
  apt: name="{{ apt_packages }}" state=latest
  become: true
  when:
    - 'ansible_os_family == "Ubuntu"''
    - "'apt_packages' | run_only_after"

- import_tasks: pipx.yml
  when: ansible_os_family == "Ubuntu"
