- name: Set system defaults
  script: set-defaults.sh
  changed_when: false

- name: Configure dock applications
  template:
    src: configure-dock.sh.j2
    dest: /tmp/configure-dock.sh
    mode: '0755'
  register: dock_script

- name: Apply dock configuration
  shell: /tmp/configure-dock.sh
  when: dock_script.changed
  changed_when: true

- name: Clean up dock configuration script
  file:
    path: /tmp/configure-dock.sh
    state: absent

- name: Ensure iCloud Drive is linked to ~/iCloud
  file:
    src: "{{dotfiles_user_home}}/Library/Mobile Documents/com~apple~CloudDocs"
    dest: "{{dotfiles_user_home}}/iCloud"
    state: link
  when: icloud_enabled|bool

- name: Install mac-specific homebrew packages
  homebrew: name={{item}} state=present
  with_items: "{{mac_homebrew_packages}}"

- name: Check which cask apps are already installed
  shell: brew list --cask {{item}} 2>/dev/null || echo "not_installed"
  with_items: "{{mac_cask_packages}}"
  register: cask_check_result
  failed_when: false
  changed_when: false

- name: Install Mac apps with homebrew cask (only if not already installed)
  homebrew_cask: name={{item.item}} state=present
  with_items: "{{cask_check_result.results}}"
  when: "'not_installed' in item.stdout"

- name: Install mas
  homebrew: name=mas state=present
  when: mac_mas_packages|length > 0
  tags: mas

- name: Install Mac-App-Store-only apps with mas
  command: mas install {{item.id}}
  args:
    creates: "/Applications/{{item.name}}.app"
  with_items: "{{mac_mas_packages}}"
  when: mac_mas_packages|length > 0
  tags: mas
