---
- name: Create config and cache directories for beszel
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ '~/.config/beszel' | expanduser }}"
    - "{{ '~/.cache/beszel' | expanduser }}"

- name: Create beszel agent environment file
  template:
    src: "beszel-agent.env.j2"
    dest: "{{ '~/.config/beszel/beszel-agent.env' | expanduser }}"
    mode: '0644'

- name: Add beszel tap to Homebrew
  command: brew tap henrygd/beszel
  changed_when: false

- name: Install beszel-agent using Homebrew
  homebrew:
    name: beszel-agent
    state: present

- name: Create com.woodrow.beszel-agent.plist in ~/Library/LaunchAgents
  template:
    src: "com.woodrow.beszel-agent.plist.j2"
    dest: "{{ '~/Library/LaunchAgents/com.woodrow.beszel-agent.plist' | expanduser }}"

- name: Load beszel-agent service with launchctl
  command: "launchctl load {{ '~/Library/LaunchAgents/com.woodrow.beszel-agent.plist' | expanduser }}"
  changed_when: false
