action_id: trunk-share-with-everyone
date: 2023-08-03 02:12:44
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1691028764
full_timestamp:
  nanos: 699709000
  seconds: 1691028764
trunk_version: 1.13.0
